# Generated by Django 5.1.4 on 2025-01-05 22:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF')], max_length=10)),
                ('file_path', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDFDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.IntegerField()),
                ('page_width', models.FloatField()),
                ('page_height', models.FloatField()),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.uploadedfile')),
            ],
        ),
        migrations.CreateModel(
            name='ImageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('channels', models.IntegerField()),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.uploadedfile')),
            ],
        ),
    ]
